### ISSUE TITLE
5.1 - Basic

### ISSUE THREAD

**Issue by Crola1702** [Crola1702/playground_repo#10]
# Docker Compose: Basic

## What is Docker Compose

When working with containers, it is common for users to find themselves running multiple containers simultaneously. Each container may require different runtime configurations, such as bind mounts, environment variables, or port mappings, among others. Managing these configurations manually can quickly become cumbersome and error-prone. Ensuring that each container has the correct settings and coordinating their interactions can be a time-consuming and complex task.

This is where Docker Compose comes to the rescue. It provides a powerful solution for managing and orchestrating multi-container applications. By using a single configuration file, Docker Compose allows you to easily spin up all the necessary containers with their specific configurations and manage their lifecycles as a cohesive unit.

Note: Docker Compose is a technology that is recommended to use only in development environments. Orchestration tools are better suited for managing production-grade deployment (like [Docker Swarm](https://docs.docker.com/engine/swarm/) or [Kubernetes](https://kubernetes.io/)).

## Syntax

Docker Compose configuration files are written in YAML format. There are multiple keywords that you will use to properly configure your multi-container application. Let's dive into the most important ones:

- `services`: This keyword is used to define the individual containers that make up your application. Each service represents a **container** and its configuration. Each service is identified by a unique name and can deploy multiple containers if desired.

- `image`: This attribute specifies the Docker image to be used for a service. The image is searched locally, and if not found, is pulled from a registry.

- `build`: Instead of using a pre-built image, you can specify a build context to build a custom image for a service. The build keyword allows you to provide a path to the directory containing the Dockerfile and any additional build instructions or dependencies required for building the image.

- `networks`: Networks allow you to define and manage the network connections between containers. Docker Compose automatically creates a network for your application and assigns each service to it by default, but can be manually configured to suit the network requirements.

- `volumes`: Declares the volumes or bind mounts to be mounted in a container. Volumes can be used for sharing files between containers, storing databases or logs, or persisting other types of data.

- `environment`: This keyword allows you to set environment variables within a container. Environment variables are commonly used to configure application settings, such as database connection strings or API keys.

- `ports`: This keyword enables you to specify the port mappings between the container and the host system. Bear in mind that this list will be affected by the network configuration that you choose (if `host` or `none`), or the port mappings other containers use (if a given port is already being used).

### Practice

To better understand Docker Compose, we will follow the example [react-express-mongodb](https://github.com/docker/awesome-compose/tree/master/react-express-mongodb) from the Awesome Compose repository.

- Let's set up our workspace:

    1. Create a local directory to store your `solution` and the `awesome-compose` repository:

        ``` bash
        mkdir -p docker_ws/solution && cd docker_ws && git clone https://github.com/docker/awesome-compose.git 
        ```

    1. Copy the `frontend` and `backend` folders from the example into your `solution` folder:

        ``` bash
        cp -r awesome-compose/react-express-mongodb/frontend solution && cp -r awesome-compose/react-express-mongodb/backend solution
        ```

    1. Create the compose file in the root `solution` directory:

        ``` bash
        cd solution && touch docker-compose.yaml
        ```

    1. Open your favorite text editor in this folder.

- First, we will define the compose version. In this case, we will set `3.8`, since at the moment of writing this document, it's the latest stable version:

    ``` yaml
    version: "3.8"
    ```

- Then, we will define the three `services` that we will use. These are `frontend`, `backend` and the database `mongo`.

    ``` yaml
    services:
        frontend:
            ...
        backend:
            ...
        mongo:
            ...
    ```

    Below each service, we will define its configuration.

- Additionally, we will define two networks, that will connect our containers. The first one is meant for the connection between `frontend<->backend` (called `react-express`) and the other one will be for the connection between `backend<->mongo`:

    ``` yaml
    networks:
        react-express:
        express-mongo:
    ```

    Here, docker will create both networks using the default `bridge` driver configuration.

- We will as well define a volume for our database:

    ``` yaml
    volumes:
        data:
    ```

- Let's first populate the `frontend` service configuration:

    1. We would like to build the image locally, using the Dockerfile defined in the frontend directory. If you look at this file, you will see that it contains two stages (`development` and `dev-envs`). Here, we will use the `development` one.

        ``` yaml
        frontend:
            build:
                context: frontend
                target: development
        ```

        Here, we will use the sub-keywords `context` and `target` to define the relative folder where the Dockerfile is stored, and the stage to compile.

    1. Then, let's set the port mapping (`8080:3000`) and the network to use:

        ``` yaml
        frontend:
            ...
            ports:
                - 8080:3000
            networks:
                - react-express
        ```

    1. Now, we will create the volumes and bind mounts for the service. Here, we would like to mount the `frontend` folder inside the `/usr/src/app` directory, and create a volume for the `node_modules`:

        ``` yaml
        frontend:
            ...
            volumes:
                - ./frontend:/usr/src/app
                - /usr/src/app/node_modules
        ```

        As you can see for the `node_modules` volume we didn't have to define a name for the volume. By just specifying the path inside the container, docker will create a volume for us.

    1. Finally, we will set two keywords that customize the lifecycle of our container:

        ``` yaml
        frontend:
            ...
            restart: always
            depends_on: 
                - backend
        ```

        The `restart` keyword set to `always` forces our service to always restart if it crashes (deletes and creates a new container).

        The `depends_on` keyword will force the `backend` service to always run when running the `frontend` one. This is used when you desire to only trigger one container in the configuration. In this case, if you ask to run the frontend service, it will trigger as well the backend one (running it first).

- The configuration for the `backend` service is pretty similar:

    1. We will use the Dockerfile inside the `backend` folder, asking to compile the `development` stage. We will set similar volumes and lifecycle conditions:

    ``` yaml
    backend:
        build:
            context: backend
            target: development
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
        depends_on:
            - mongo
    ```

    1. The difference here is that we will connect the `backend` service to both the `mongo` and `frontend` services:

    ``` yaml
    backend:
        ...
        networks:
            - express-mongo
            - react-express
    ```

- Finally, let's configure the `mongo` database service:

    1. For this service, we will use the pre-built image `mongo:4.2.0` stored from Dockerhub:

    ``` yaml
    mongo:
        image: mongo:4.2.0
    ```

    1. For the volumes, we will create a `data` volume for storage:

    ``` yaml
    mongo:
        ...
        volumes:
            - data:/data/db
    ```

    As you can see, we defined here a name, not a path, for the `data` volume.

    1. Lastly, we will set the network and lifecycle conditions:

    ``` yaml
    mongo:
        ...
        networks:
            - express-mongo
        restart: always
    ```

- The complete configuration should look like this:

    ``` yaml
    version: "3.8"

    services:
        frontend:
            build:
                context: frontend
                target: development
            ports:
                - 8080:3000
            networks:
                - react-express
            volumes:
                - ./frontend:/usr/src/app
                - /usr/src/app/node_modules
            restart: always
            depends_on: 
                - backend
    
        backend:
            build:
                context: backend
                target: development
            volumes:
                - ./backend:/usr/src/app
                - /usr/src/app/node_modules
            restart: always
            depends_on:
                - mongo
            networks:
                - express-mongo
                - react-express
    
        mongo:
            image: mongo:4.2.0
            volumes:
                - data:/data/db
            networks:
                - express-mongo
            restart: always
            
    networks:
        react-express:
        express-mongo:
    volumes:
        data:
    ```

- To run our multi-container application, let's use the following command:

    ``` yaml
    docker compose up
    ```

    If the configuration is correct, you should see in the output log how the three containers are built and brought up. Here, you should be able to go to your browser url `localhost:8080`. There, you can interact with the application.

  - [ ] Upload a picture of the localhost web page, as well as the output log.

- To bring the system down, type `ctrl+C` in the terminal, and then run:

    ``` bash
    docker compose down
    ```

## Environment variables

As it was seen in section `1.3`, environment variables are really important when dealing with containers. They allow us to configure applications for their runtime operation, and with compose, you can have an even more powerful tool to tweak your services for different purposes.

First, we need to understand that, as in many other programming languages, there are two stages to create a var: **define** it and **initialize** it.

You can define the variable under the `environment` keyword:

``` yaml
version: "3.8"

services:
    backend:
        ...
        environment:
            - APP_PORT
```

Once defined, there are three possible ways to initialize them with a value:

1. Hard code their values:

    ``` yaml
    ...
    environment:
        - APP_PORT=8080
    ```

1. Create a `.env` file with the variables and their respective values:

    ``` sh
    $ cat .env
    APP_PORT=8080

    $ cat compose.yml
    ...
    environment:
        - APP_PORT=${APP_PORT}
    ```

1. Read them from the host shell variables. If your shell terminal has a define value for the variable, compose will just re use that value.

    ``` sh
    $ export APP_PORT=8080

    $ cat compose.yml
    ...
    environment:
        - APP_PORT=${APP_PORT}
    ```

If compose can not find the value for a defined variable, you can define *default* values:

``` yaml
...
environment:
    - APP_PORT=${APP_PORT:-8080}
```

# References

 - [Environment Variables in Compose](https://docs.docker.com/compose/environment-variables/)
