### ISSUE TITLE
6.1 - Running Containers in CI with Github Actions

### ISSUE THREAD

**Issue by Crola1702** [Crola1702/playground_repo#12]
# Running Containers in CI with GitHub Actions

In this lesson, you will learn how to build and push a docker image using GitHub Actions for continuous integration (CI) workflows.

**Note**: Only people with admin permissions have the ability to set up secrets on Github (you will see what a secret is below). Please **create an issue tagging a Professor to request setting up the secrets**. The Professor will give you admin permissions and as soon as the secrets are added, **clarify in the issue that the corresponding task is complete**; your assigned Professor will revoke the permissions granted.

## Concepts

To understand how to create a Github action, we first need to understand what they are comprised of. Read [The components of Github Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#the-components-of-github-actions) to review all the needed concepts for this lesson.

- In case you have any questions, please write them down in the issue so that we can have a further discussion around the subject.

### Step 1: Creating a GitHub Actions Workflow

Inside your repository, navigate to the `.github/workflows` directory.
Create a new YAML file, e.g., `build.yaml`, for your workflow configuration.
Define the `name` and `trigger` events for the workflow using the `name` and `on` keywords.
For example, you can trigger the workflow on push events to the main branch:

```yaml
name: Build

on:
  push:
    branches:
      - main
```

Configure the workflow to run on a virtual environment with the desired operating system using the `jobs` keyword.
For example, to run on Ubuntu, use the `ubuntu-latest` environment:

```yaml
jobs:
  docker:
    runs-on: ubuntu-latest
```

Specify the steps for the job using the `steps` keyword.
Add a step to check out the repository code using the `actions/checkout` action.
This step ensures that the workflow has access to your repository's code:

```yaml
steps:
  - name: Checkout repository
    uses: actions/checkout@v2
```

Add the `docker/metadata` action to tag and label Docker images with information of the github repository. The `images` parameter is a group of base names that will be used when generating a new image. To see more information around the usage of this action, go [here](https://github.com/docker/metadata-action#usage).

```yaml
steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: name/app  # Replace with <username>/<image_name>
```

Add a step to install and set up the Docker environment with BuildKit enabled using the `docker/setup-buildx-action` action.
This step sets up the required Docker environment:

```yaml
steps:
  - name: Checkout repository
    uses: actions/checkout@v2
  
  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: name/app  # Replace with <username>/<image_name>

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
```

Add a new step before the "Log in to Docker Hub" step to log in to Docker Hub using the `docker/login-action` action.
This step authenticates the workflow with your Docker Hub credentials:

```yaml
steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: name/app  # Replace with <username>/<image_name>

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  - name: Log in to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
```

To store the Docker Hub Credentials as Secrets, go to the "Settings" tab in your Github repository.
In the left sidebar, click on "Secrets" to navigate to the repository secrets page.
Click on "New repository secret" to add a new secret.
Enter `DOCKERHUB_USERNAME` as the name of the secret and your Docker Hub username as the value.
Repeat the above step for `DOCKERHUB_ACCESS_TOKEN`, using the access token you generated.

Add a step to build and push the image using the `docker/build-push-action` action.
This step builds the Docker image and pushes it to a remote registry. We will list the several parameters used in this action and their purpose:
- `push`: if set to true, the image will be pushed to a remote registry. If set to false, the image will be built but not pushed to a registry.
- `tags`: specifies the tags for the Docker image, which in this case are set according to the meta step output.
-`labels`: specifies the labels for the Docker image, which will also be set according to the meta step output.
-`context`: specifies the context of the Docker image.
- `file`: specifies the Dockerfile used, in case there are several Dockerfiles in the repository.

```yaml
steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: name/app  # Replace with <username>/<image_name>

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  - name: Build and push
    uses: docker/build-push-action@v4
    with:
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      context: .
      file: path/to/Dockerfile
```

Save and commit the workflow file to your repository.

### Step 2: Building and pushing an image with GitHub Actions

Push your changes to the main branch of your GitHub repository.
Navigate to the `Actions` tab on your repository page in GitHub.
You should see the workflow you created listed.
Click on the workflow name to view the workflow runs.
If the workflow has not run automatically, you can manually trigger it by clicking on the `Run workflow` button.
Once the workflow is running, you can monitor the progress and view the logs for each step.
If the workflow completes successfully, you have successfully pushed a Docker image to your Dockerhub repository using GitHub Actions.

## Congratulations!
You have learned how to build and push an image using GitHub Actions for CI workflows. By leveraging Docker and GitHub Actions together, you can automate the deployment and testing of multi-container applications. Remember to explore additional features and actions provided by GitHub Actions to customize and enhance your CI workflows further.

## Practice

- [ ] Create a github workflow to build and push the Go application.

### Act tool

Use the [act tool](https://github.com/nektos/act) to test locally if your Github action is working as expected.
